image: ubuntu1804

install:
# Install Android SDK
- ANDROID_SDK_URL="https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip"
- export ANDROID_SDK_ROOT="/usr/lib/android-sdk"
- sudo mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools"
- 'sudo chown -R $(id -u):$(id -g) "${ANDROID_SDK_ROOT}"'
- mkdir -p ~/.android
# Silence warning.
- touch ~/.android/repositories.cfg
- ANDROID_SDK_ARCHIVE="${ANDROID_SDK_ROOT}/archive"
- wget --progress=dot:giga "${ANDROID_SDK_URL}" -O "${ANDROID_SDK_ARCHIVE}"
- unzip -q -d "${ANDROID_SDK_ROOT}/cmdline-tools" "${ANDROID_SDK_ARCHIVE}"
- mv "${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools" "${ANDROID_SDK_ROOT}/cmdline-tools/tools"
- PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
# Suppressing output of sdkmanager to keep log size down
# (it prints install progress WAY too often).
- export JAVA_HOME=$JAVA_HOME_15_X64
- export PATH=$JAVA_HOME/bin:$PATH
- java --version
- echo $JAVA_HOME
- sdkmanager --version
- echo y | sdkmanager "tools" > /dev/null
- echo y | sdkmanager "build-tools;28.0.3" > /dev/null
- echo y | sdkmanager "platforms;android-30" > /dev/null
- echo y | sdkmanager "platform-tools" > /dev/null
- echo y | sdkmanager "cmdline-tools;latest" > /dev/null
- echo y | sdkmanager "extras;android;m2repository" > /dev/null
- echo y | sdkmanager "extras;google;m2repository" > /dev/null
- echo y | sdkmanager "patcher;v4" > /dev/null
- rm "${ANDROID_SDK_ARCHIVE}"

# Install Flutter SDK
- export LANG=en_US.UTF-8
- curl https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.0.1-stable.tar.xz -o flutter_linux.tar.xz
- tar -xf flutter_linux.tar.xz -C $HOME
- export PATH="$PATH:$HOME/flutter/bin"
- flutter --version
- flutter doctor

# Silence warnings when accepting android licenses.
- mkdir -p ~/.android
- touch ~/.android/repositories.cfg

build: off
test: off
