image: ubuntu1804

install:
# Install Flutter SDK
- export LANG=en_US.UTF-8
#- curl https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.0.1-stable.tar.xz -o flutter_linux.tar.xz
#- tar -xf flutter_linux.tar.xz -C $HOME
#- export PATH="$PATH:$HOME/flutter/bin"
#- flutter --version
#- flutter doctor

# Install Android SDK
- ANDROID_SDK_URL="https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip"
- ANDROID_TOOLS_ROOT="/usr/lib/android-sdk"
- export ANDROID_SDK_ROOT=${ANDROID_TOOLS_ROOT}
- sudo mkdir -p "${ANDROID_TOOLS_ROOT}"
- 'sudo chown $(id -u):$(id -g) "${ANDROID_TOOLS_ROOT}"'
- mkdir -p ~/.android
# Silence warning.
- touch ~/.android/repositories.cfg
- ANDROID_SDK_ARCHIVE="${ANDROID_TOOLS_ROOT}/archive"
- wget --progress=dot:giga "${ANDROID_SDK_URL}" -O "${ANDROID_SDK_ARCHIVE}"
- unzip -q -d "${ANDROID_TOOLS_ROOT}" "${ANDROID_SDK_ARCHIVE}"
- PATH="${ANDROID_TOOLS_ROOT}/cmdline-tools/bin:${PATH}"
#- mv "${ANDROID_TOOLS_ROOT}/cmdline-tools" "${ANDROID_TOOLS_ROOT}/tools"
# Suppressing output of sdkmanager to keep log size down
# (it prints install progress WAY too often).
- echo y | sdkmanager "tools" > /dev/null
- echo y | sdkmanager "build-tools;28.0.3" > /dev/null
- rm "${ANDROID_SDK_ARCHIVE}"


# Silence warnings when accepting android licenses.
- mkdir -p ~/.android
- touch ~/.android/repositories.cfg

build: off
test: off
